---
title: "L01 Review"
subtitle: "Data Science 3 with R (STAT 301-3)"
author: "Lidia Mora Gallegos"
pagetitle: "L01 Lidia Mora Gallegos"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin   
---

::: {.callout-tip icon="false"}
## Github Repo Link

[Github Repo Link](https://github.com/stat301-3-2026-spring/l01-review-lmg2027)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution

1. EDA 
2. Split the data
3. feature engineering
4. fold training data
5. define recipe 
6. set engine with tuning parameters
7. create workflow
8. tune
9. compare models - select best 
10. fit to full training data 
11. evaluate model using actual 

:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution

Supervised learning is task driven and refers to a problem where you predict a specific variable. In a supervised learning problem you have access to the target variable. Your data is in the form of a target variable y and prediction variables x. 
In an unsupervised learning problem you don't do prediction at all. Unsupervised learning problems simply look for patterns within the data. 

:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

Descriptive models describe or illustrate the characteristics of a given dataset. 

:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

Inferential models test a hypothesis. 

:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

Predictive models make the most accurate prediction possible for new data. 

:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

Empirically driven models are based on numbers. 

:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

Mechanistic is often associated with 

:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

V-fold cross validation takes the training dataset and splits it into v-many folds and w-many repeats. Stratified sampling can also be used to ensure there is an even distribution of the target variable in each fold. When this is fit to models it uses 4 of the sections (acting as the training set) to fit to the model and the remaining section (acting as the testing set) to calculate performance metrics (in this case, RMSE). After all 5 combinations are done it takes the average of the performance metrics and provides it as an estimate of the testing RMSE. We use v-fold cross validation to improve the accuracy of estimates and prevent over fitting. 

:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

